#!/bin/bash
update_apps() {
  # 1. Convert the arguments to an array using (@)
  apps=("$@")
  
  # 2. Loop through the "apps" array using [@] to expand all elements
  for app in "${apps[@]}"
  do
    echo "Checking $app"
  done
  
  # 3. Loop through the positional arguments directly using "$@"
  for app in "$@"
  do
    echo "Updating $app"
  done
}

update_apps "Photos" "Browser" "Documents"